services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN}
    depends_on:
      - traefik
    networks:
      - edge
    labels:
      autoheal: "true"
      com.centurylinklabs.watchtower.enable: "true"

networks:
  edge:
    name: login-frontend-edge
