http:
  routers:
    frontend:
      rule: "Host(`login.ofcoliva.com.br`)"
      entryPoints:
        - websecure
      service: frontend-wrr
      tls:
        certResolver: letsencrypt
      middlewares:
        - frontend-ratelimit
        - frontend-secureheaders

    frontend-http:
      rule: "Host(`login.ofcoliva.com.br`)"
      entryPoints:
        - web
      service: frontend-wrr
      middlewares:
        - redirect-to-https

    frontend-local:
      rule: "Host(`localhost`) || Host(`127.0.0.1`)"
      entryPoints:
        - web
      service: frontend-wrr
      middlewares:
        - frontend-ratelimit
        - frontend-secureheaders

    frontend-local-secure:
      rule: "Host(`localhost`) || Host(`127.0.0.1`)"
      entryPoints:
        - websecure
      service: frontend-wrr
      tls: {}
      middlewares:
        - frontend-ratelimit
        - frontend-secureheaders

  services:
    frontend-wrr:
      weighted:
        services:
          - name: frontend-blue
            weight: 0
          - name: frontend-green
            weight: 100

    frontend-blue:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://frontend-blue:8080"

    frontend-green:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://frontend-green:8080"

  middlewares:
    frontend-ratelimit:
      rateLimit:
        average: 100
        burst: 50
    frontend-secureheaders:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: strict-origin-when-cross-origin
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
